### ISSUE TITLE
tests/test_plugin.py block error

### ISSUE THREAD

**Issue by zqqw** [asciidoc-py/asciidoc-py#243]
Thank you for the new release, I thought I would try it so quickly modified the PKGBUILD:
```
$ diff -u asciidoc/PKGBUILD PKGBUILD 
--- asciidoc/PKGBUILD	2022-02-20 21:24:38.824079823 +0000
+++ PKGBUILD	2022-02-20 21:09:38.297490583 +0000
@@ -10,8 +10,8 @@
 # Contributor: Daniel J Griffiths <ghost1227@archlinux.us>
 
 pkgname=asciidoc
-pkgver=10.1.2
-pkgrel=2
+pkgver=10.1.3
+pkgrel=1
 pkgdesc='Text document format for short documents, articles, books and UNIX man pages'
 arch=('any')
 url='https://asciidoc.org/'
@@ -28,17 +28,18 @@
             'w3m: text generation'
             'lynx: alternative text generation')
 source=("https://github.com/asciidoc-py/asciidoc-py/releases/download/$pkgver/$pkgname-$pkgver.tar.gz")
-sha256sums=('0bfcebf4d0419323c8b4903676b05259847e6534c82a2629a0c852e621de7c47')
-b2sums=('a00ade1a849ffed98d10ddbbca5300e6f9fca9fc60663ff6e59979613a013b408829d35d9362cdf830ef08cd494ca4a47dab919ce29ce7111ee0fdaa3e301f24')
+sha256sums=('SKIP')
+#sha256sums=('0bfcebf4d0419323c8b4903676b05259847e6534c82a2629a0c852e621de7c47')
+#b2sums=('a00ade1a849ffed98d10ddbbca5300e6f9fca9fc60663ff6e59979613a013b408829d35d9362cdf830ef08cd494ca4a47dab919ce29ce7111ee0fdaa3e301f24')
 
 prepare() {
-  cd ${pkgname}-py-${pkgver}
+  cd ${pkgname}-${pkgver}
   # https://github.com/asciidoc-py/asciidoc-py/issues/234
   autoconf
 }
 
 build() {
-  cd ${pkgname}-py-${pkgver}
+  cd ${pkgname}-${pkgver}
   # https://github.com/asciidoc-py/asciidoc-py/issues/234#issuecomment-1045970138
   ./configure \
       --docdir /usr/share/doc/$pkgname \
@@ -48,12 +49,12 @@
 }
 
 check() {
-  cd ${pkgname}-py-${pkgver}
+  cd ${pkgname}-${pkgver}
   make test
 }
 
 package() {
-  cd ${pkgname}-py-${pkgver}
+  cd ${pkgname}-${pkgver}
   make DESTDIR="${pkgdir}" install
   make DESTDIR="${pkgdir}" docs
   install -Dm0644 -t "$pkgdir/usr/share/man/man1/" doc/*.1

```

But anyway, the build fails on the tests with another block error, when I ran the test from the cmdline it said this:

```
/tmp/asciidoc/src/asciidoc-10.1.3$ python tests/test_plugin.py
Traceback (most recent call last):
  File "/tmp/asciidoc/src/asciidoc-10.1.3/tests/test_plugin.py", line 3, in <module>
    from asciidoc.message import Message
  File "/usr/lib/python3.10/site-packages/asciidoc/__init__.py", line 11, in <module>
    from .api import AsciiDocAPI
  File "/usr/lib/python3.10/site-packages/asciidoc/api.py", line 1, in <module>
    from . import asciidoc
  File "/usr/lib/python3.10/site-packages/asciidoc/asciidoc.py", line 35, in <module>
    from .blocks.table import parse_table_span_spec, Cell, Column
ModuleNotFoundError: No module named 'asciidoc.blocks'
```
Possibly I needed to make more mods to the PKGBUILD, apologies in advance if that is the case!

**Comment by MasterOdin** [comment]
I'm not sure `python tests/test_plugin.py` will work directly, it relies on pytest handling adding the asciidoc module to the syspath for imports, and so you'd need to do `python -m pytest tests/test_plugin.py`.

**Comment by zqqw** [comment]
It fails like that too, and with "make test" which is what caused the PKGBUILD to quit, that's your test in this package, the above was just me trying to run it individually afterwards, but obviously incorrectly!
```
/tmp/asciidoc/asciidoc-10.1.3$ autoconf
/tmp/asciidoc/asciidoc-10.1.3$ ./configure
checking for a sed that does not truncate output... /usr/bin/sed
checking whether ln -s works... yes
checking for a BSD-compatible install... /usr/bin/install -c
configure: creating ./config.status
config.status: creating Makefile
/tmp/asciidoc/asciidoc-10.1.3$ make
make: Nothing to be done for 'all'.
/tmp/asciidoc/asciidoc-10.1.3$ make test
python3 -m asciidoc.asciidoc --doctest
asciidoc: All doctests passed
python3 -m pytest
============================================================================= test session starts ==============================================================================
platform linux -- Python 3.10.2, pytest-6.2.5, py-1.11.0, pluggy-0.13.1
rootdir: /tmp/asciidoc/asciidoc-10.1.3
plugins: mock-3.7.0
collected 59 items                                                                                                                                                             

tests/test_a2x.py ...                                                                                                                                                    [  5%]
tests/test_asciidoc.py ..........                                                                                                                                        [ 22%]
tests/test_collections.py ...                                                                                                                                            [ 27%]
tests/test_plugin.py F                                                                                                                                                   [ 28%]
tests/test_utils.py ..........................................                                                                                                           [100%]

=================================================================================== FAILURES ===================================================================================
_______________________________________________________________________________ test_plugin_list _______________________________________________________________________________

capsys = <_pytest.capture.CaptureFixture object at 0x7fa5b92b1db0>

    def test_plugin_list(capsys) -> None:
        plugin = Plugin('backend', Message(None, None, CONFIG, None), CONFIG)
        plugin.list([])
        captured = capsys.readouterr()
        backend_dir = PLUGIN_DIR / 'backends'
>       assert captured.out == "{}\n{}\n".format(backend_dir / 'bar', backend_dir / 'foo')
E       AssertionError: assert '' == '/tmp/asciido...ackends/foo\n'
E         - /tmp/asciidoc/asciidoc-10.1.3/tests/__test_data__/plugin/backends/bar
E         - /tmp/asciidoc/asciidoc-10.1.3/tests/__test_data__/plugin/backends/foo

tests/test_plugin.py:17: AssertionError
=============================================================================== warnings summary ===============================================================================
asciidoc/a2x.py:289
  /tmp/asciidoc/asciidoc-10.1.3/asciidoc/a2x.py:289: DeprecationWarning: invalid escape sequence '\A'
    mo = re.search(b'\A<\?xml.* encoding="(.*?)"', contents)

asciidoc/a2x.py:376
  /tmp/asciidoc/asciidoc-10.1.3/asciidoc/a2x.py:376: DeprecationWarning: invalid escape sequence '\s'
    mo = re.search(b'^//\s*a2x:', line)

tests/test_asciidoc.py: 20 warnings
  <unknown>:1: DeprecationWarning: invalid escape sequence '\S'

tests/test_asciidoc.py::test_ignore_attribute[link:\\{attach}file\\{0}.txt[file\\{bar}too\\{1}]-<div class="paragraph"><p><a href="{attach}file{0}.txt">file{bar}too{1}</a></p></div>\r\n]
tests/test_asciidoc.py::test_ignore_attribute[link:\\{attach}file\\{0}.txt[file\\{bar}too\\{1}]-<div class="paragraph"><p><a href="{attach}file{0}.txt">file{bar}too{1}</a></p></div>\r\n]
tests/test_asciidoc.py::test_ignore_attribute[image:\\{attach}file.jpg[\\{bar}?]-<div class="paragraph"><p><span class="image">\r\n<img src="{attach}file.jpg" alt="{bar}?" />\r\n</span></p></div>\r\n]
tests/test_asciidoc.py::test_ignore_attribute[image:\\{attach}file.jpg[\\{bar}?]-<div class="paragraph"><p><span class="image">\r\n<img src="{attach}file.jpg" alt="{bar}?" />\r\n</span></p></div>\r\n]
  <unknown>:1: DeprecationWarning: invalid escape sequence '\{'

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=========================================================================== short test summary info ============================================================================
FAILED tests/test_plugin.py::test_plugin_list - AssertionError: assert '' == '/tmp/asciido...ackends/foo\n'
================================================================== 1 failed, 58 passed, 26 warnings in 1.21s ===================================================================
make: *** [Makefile:144: test] Error 1

```
This is with all the build deps installed as per the PKGBUILD list. It seemed suspicious this test fails when it also involves "blocks" but perhaps there is some other reason.
If the tests are not run, the resulting package does seem to build the pakku man pages sucessfully though.

**Comment by MasterOdin** [comment]
Thanks for the additional information, I've opened a PR to fix it. The current method to build the dist files is clearly far too brittle 😬 .
